# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'


- task: MSBuild@1
  inputs:
    solution: 'sln\OData.Net45.sln' #'sln\OData.Net45.sln'
    restoreNugetPackages: true
    msbuildArchitecture: 'x64'
    platform: 'x64'
- 
- task: VSTest@2
  inputs:
    testSelector: 'testAssemblies'
    testAssemblyVer2: |
      **\*test*.dll
      !**\*TestAdapter.dll
      !**\obj\**
    searchFolder: '$(System.DefaultWorkingDirectory)'
    vsTestVersion: 'toolsInstaller'

 